//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPExtended.Applications.WebMediaPortal.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MPExtended.Applications.WebMediaPortal.Strings.FormStrings", typeof(FormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist/Artist,Album/Albums.
        /// </summary>
        public static string AvailableMusicViews {
            get {
                return ResourceManager.GetString("AvailableMusicViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client service.
        /// </summary>
        public static string ClientService {
            get {
                return ResourceManager.GetString("ClientService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default media streaming profile.
        /// </summary>
        public static string DefaultMediaStreamingProfile {
            get {
                return ResourceManager.GetString("DefaultMediaStreamingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default music streaming profile.
        /// </summary>
        public static string DefaultMusicStreamingProfile {
            get {
                return ResourceManager.GetString("DefaultMusicStreamingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default.
        /// </summary>
        public static string DefaultSkinName {
            get {
                return ResourceManager.GetString("DefaultSkinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default TV Group.
        /// </summary>
        public static string DefaultTVGroup {
            get {
                return ResourceManager.GetString("DefaultTVGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default TV streaming profile.
        /// </summary>
        public static string DefaultTVStreamingProfile {
            get {
                return ResourceManager.GetString("DefaultTVStreamingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct: best performance, works only on local network.
        /// </summary>
        public static string DirectStreamingProfileDescription {
            get {
                return ResourceManager.GetString("DirectStreamingProfileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct when possible, otherwise proxied.
        /// </summary>
        public static string DirectWhenPossibleDescription {
            get {
                return ResourceManager.GetString("DirectWhenPossibleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable the album player for music?.
        /// </summary>
        public static string EnableAlbumPlayer {
            get {
                return ResourceManager.GetString("EnableAlbumPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid MAS URL.
        /// </summary>
        public static string ErrorNoValidClientService {
            get {
                return ResourceManager.GetString("ErrorNoValidClientService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid language.
        /// </summary>
        public static string ErrorNoValidLanguage {
            get {
                return ResourceManager.GetString("ErrorNoValidLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid media streaming profile.
        /// </summary>
        public static string ErrorNoValidMediaProfile {
            get {
                return ResourceManager.GetString("ErrorNoValidMediaProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid movie database.
        /// </summary>
        public static string ErrorNoValidMovieDatabase {
            get {
                return ResourceManager.GetString("ErrorNoValidMovieDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid music database.
        /// </summary>
        public static string ErrorNoValidMusicDatabase {
            get {
                return ResourceManager.GetString("ErrorNoValidMusicDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid music streaming profile.
        /// </summary>
        public static string ErrorNoValidMusicProfile {
            get {
                return ResourceManager.GetString("ErrorNoValidMusicProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid music layout.
        /// </summary>
        public static string ErrorNoValidMusicView {
            get {
                return ResourceManager.GetString("ErrorNoValidMusicView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify a valid TAS URL.
        /// </summary>
        public static string ErrorNoValidServerService {
            get {
                return ResourceManager.GetString("ErrorNoValidServerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid skin.
        /// </summary>
        public static string ErrorNoValidSkin {
            get {
                return ResourceManager.GetString("ErrorNoValidSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid TVgroup.
        /// </summary>
        public static string ErrorNoValidTVGroup {
            get {
                return ResourceManager.GetString("ErrorNoValidTVGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid TV streaming profile.
        /// </summary>
        public static string ErrorNoValidTVProfile {
            get {
                return ResourceManager.GetString("ErrorNoValidTVProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a valid TV show database.
        /// </summary>
        public static string ErrorNoValidTVShowDatabase {
            get {
                return ResourceManager.GetString("ErrorNoValidTVShowDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to the specified client service.
        /// </summary>
        public static string FailedToConnectToClient {
            get {
                return ResourceManager.GetString("FailedToConnectToClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to the specified server service.
        /// </summary>
        public static string FailedToConnectToServer {
            get {
                return ResourceManager.GetString("FailedToConnectToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} field is required.
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LogOnPassword {
            get {
                return ResourceManager.GetString("LogOnPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string LogOnRememberMe {
            get {
                return ResourceManager.GetString("LogOnRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LogOnUsername {
            get {
                return ResourceManager.GetString("LogOnUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie database.
        /// </summary>
        public static string MovieDatabase {
            get {
                return ResourceManager.GetString("MovieDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediaPortal server (MAS).
        /// </summary>
        public static string MultiseatMAS {
            get {
                return ResourceManager.GetString("MultiseatMAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Server (TAS).
        /// </summary>
        public static string MultiseatTAS {
            get {
                return ResourceManager.GetString("MultiseatTAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music database.
        /// </summary>
        public static string MusicDatabase {
            get {
                return ResourceManager.GetString("MusicDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music layout.
        /// </summary>
        public static string MusicView {
            get {
                return ResourceManager.GetString("MusicView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxied: instantly stops timeshiftings, works over the internet.
        /// </summary>
        public static string ProxiedStreamingProfileDescription {
            get {
                return ResourceManager.GetString("ProxiedStreamingProfileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        public static string ScheduleChannel {
            get {
                return ResourceManager.GetString("ScheduleChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endtime.
        /// </summary>
        public static string ScheduleEndTime {
            get {
                return ResourceManager.GetString("ScheduleEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a valid channel.
        /// </summary>
        public static string ScheduleSelectValidChannel {
            get {
                return ResourceManager.GetString("ScheduleSelectValidChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a valid schedule type.
        /// </summary>
        public static string ScheduleSelectValidType {
            get {
                return ResourceManager.GetString("ScheduleSelectValidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starttime.
        /// </summary>
        public static string ScheduleStartTime {
            get {
                return ResourceManager.GetString("ScheduleStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string ScheduleTitle {
            get {
                return ResourceManager.GetString("ScheduleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule type.
        /// </summary>
        public static string ScheduleType {
            get {
                return ResourceManager.GetString("ScheduleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string ScheduleTypeDaily {
            get {
                return ResourceManager.GetString("ScheduleTypeDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every time on every channel.
        /// </summary>
        public static string ScheduleTypeEveryTimeOnEveryChannel {
            get {
                return ResourceManager.GetString("ScheduleTypeEveryTimeOnEveryChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every time on this channel.
        /// </summary>
        public static string ScheduleTypeEveryTimeOnThisChannel {
            get {
                return ResourceManager.GetString("ScheduleTypeEveryTimeOnThisChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once.
        /// </summary>
        public static string ScheduleTypeOnce {
            get {
                return ResourceManager.GetString("ScheduleTypeOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekends.
        /// </summary>
        public static string ScheduleTypeWeekends {
            get {
                return ResourceManager.GetString("ScheduleTypeWeekends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string ScheduleTypeWeekly {
            get {
                return ResourceManager.GetString("ScheduleTypeWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly on this channel.
        /// </summary>
        public static string ScheduleTypeWeeklyOnThisChannel {
            get {
                return ResourceManager.GetString("ScheduleTypeWeeklyOnThisChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working days.
        /// </summary>
        public static string ScheduleTypeWorkingDays {
            get {
                return ResourceManager.GetString("ScheduleTypeWorkingDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (album) by {1}.
        /// </summary>
        public static string SearchResultAlbum {
            get {
                return ResourceManager.GetString("SearchResultAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (channel group).
        /// </summary>
        public static string SearchResultChannelGroup {
            get {
                return ResourceManager.GetString("SearchResultChannelGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1} on {2}).
        /// </summary>
        public static string SearchResultProgram {
            get {
                return ResourceManager.GetString("SearchResultProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (recorded on {1}).
        /// </summary>
        public static string SearchResultRecording {
            get {
                return ResourceManager.GetString("SearchResultRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (schedule).
        /// </summary>
        public static string SearchResultSchedule {
            get {
                return ResourceManager.GetString("SearchResultSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} by {1}.
        /// </summary>
        public static string SearchResultTrack {
            get {
                return ResourceManager.GetString("SearchResultTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server service.
        /// </summary>
        public static string ServerService {
            get {
                return ResourceManager.GetString("ServerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin.
        /// </summary>
        public static string Skin {
            get {
                return ResourceManager.GetString("Skin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idle.
        /// </summary>
        public static string StateIdle {
            get {
                return ResourceManager.GetString("StateIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording.
        /// </summary>
        public static string StateRecording {
            get {
                return ResourceManager.GetString("StateRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning.
        /// </summary>
        public static string StateScanning {
            get {
                return ResourceManager.GetString("StateScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeshifting.
        /// </summary>
        public static string StateTimeshifting {
            get {
                return ResourceManager.GetString("StateTimeshifting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream type.
        /// </summary>
        public static string StreamType {
            get {
                return ResourceManager.GetString("StreamType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Show database.
        /// </summary>
        public static string TVShowDatabase {
            get {
                return ResourceManager.GetString("TVShowDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username or password provided is incorrect..
        /// </summary>
        public static string UsernamePasswordIncorrect {
            get {
                return ResourceManager.GetString("UsernamePasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VLC player: enable deinterlacing by default?.
        /// </summary>
        public static string VLCPlayerEnableDeinterlacing {
            get {
                return ResourceManager.GetString("VLCPlayerEnableDeinterlacing", resourceCulture);
            }
        }
    }
}
