//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPExtended.Applications.WebMediaPortal.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MPExtended.Applications.WebMediaPortal.Strings.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        public static string AccountInformation {
            get {
                return ResourceManager.GetString("AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actor.
        /// </summary>
        public static string Actor {
            get {
                return ResourceManager.GetString("Actor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actors.
        /// </summary>
        public static string Actors {
            get {
                return ResourceManager.GetString("Actors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add schedule.
        /// </summary>
        public static string AddSchedule {
            get {
                return ResourceManager.GetString("AddSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aired {0}.
        /// </summary>
        public static string Aired {
            get {
                return ResourceManager.GetString("Aired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} by {1}.
        /// </summary>
        public static string AlbumBy {
            get {
                return ResourceManager.GetString("AlbumBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s albums.
        /// </summary>
        public static string AlbumsFromArtist {
            get {
                return ResourceManager.GetString("AlbumsFromArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All albums.
        /// </summary>
        public static string AllAlbums {
            get {
                return ResourceManager.GetString("AllAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All genres.
        /// </summary>
        public static string AllGenres {
            get {
                return ResourceManager.GetString("AllGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All movies.
        /// </summary>
        public static string AllMovies {
            get {
                return ResourceManager.GetString("AllMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel schedule.
        /// </summary>
        public static string CancelSchedule {
            get {
                return ResourceManager.GetString("CancelSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        public static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card details.
        /// </summary>
        public static string CardDetails {
            get {
                return ResourceManager.GetString("CardDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grabbing EPG.
        /// </summary>
        public static string CardGrabbingEPG {
            get {
                return ResourceManager.GetString("CardGrabbingEPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card name.
        /// </summary>
        public static string CardName {
            get {
                return ResourceManager.GetString("CardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording file.
        /// </summary>
        public static string CardRecordingFile {
            get {
                return ResourceManager.GetString("CardRecordingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTSP stream.
        /// </summary>
        public static string CardRTSPStream {
            get {
                return ResourceManager.GetString("CardRTSPStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuner cards.
        /// </summary>
        public static string Cards {
            get {
                return ResourceManager.GetString("Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrambled.
        /// </summary>
        public static string CardScrambled {
            get {
                return ResourceManager.GetString("CardScrambled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string CardState {
            get {
                return ResourceManager.GetString("CardState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeshifting file.
        /// </summary>
        public static string CardTimeshiftingFile {
            get {
                return ResourceManager.GetString("CardTimeshiftingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change profile.
        /// </summary>
        public static string ChangeProfile {
            get {
                return ResourceManager.GetString("ChangeProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        public static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection.
        /// </summary>
        public static string Collection {
            get {
                return ResourceManager.GetString("Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collections.
        /// </summary>
        public static string Collections {
            get {
                return ResourceManager.GetString("Collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to form.
        /// </summary>
        public static string CopyToForm {
            get {
                return ResourceManager.GetString("CopyToForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string CreateSchedule {
            get {
                return ResourceManager.GetString("CreateSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current CPU usage:.
        /// </summary>
        public static string CurrentCPUUsage {
            get {
                return ResourceManager.GetString("CurrentCPUUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current memory usage:.
        /// </summary>
        public static string CurrentMemoryUsage {
            get {
                return ResourceManager.GetString("CurrentMemoryUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string DiskInfoAvailable {
            get {
                return ResourceManager.GetString("DiskInfoAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk.
        /// </summary>
        public static string DiskInfoDisk {
            get {
                return ResourceManager.GetString("DiskInfoDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk information.
        /// </summary>
        public static string DiskInformation {
            get {
                return ResourceManager.GetString("DiskInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string DiskInfoSize {
            get {
                return ResourceManager.GetString("DiskInfoSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        public static string DiskInfoUsed {
            get {
                return ResourceManager.GetString("DiskInfoUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download playlist (.m3u) for usage with external player.
        /// </summary>
        public static string DownloadPlaylist {
            get {
                return ResourceManager.GetString("DownloadPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earlier.
        /// </summary>
        public static string Earlier {
            get {
                return ResourceManager.GetString("Earlier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit schedule.
        /// </summary>
        public static string EditSchedule {
            get {
                return ResourceManager.GetString("EditSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episode {0} - {1}.
        /// </summary>
        public static string EpisodeDisplay {
            get {
                return ResourceManager.GetString("EpisodeDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the information below when you report this error..
        /// </summary>
        public static string ErrorPageText {
            get {
                return ResourceManager.GetString("ErrorPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting the stream failed. Please refer to the server logs for more details..
        /// </summary>
        public static string FailedToStartStream {
            get {
                return ResourceManager.GetString("FailedToStartStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File inaccessible.
        /// </summary>
        public static string FileInaccessible {
            get {
                return ResourceManager.GetString("FileInaccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        public static string Genres {
            get {
                return ResourceManager.GetString("Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruops.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest starring:.
        /// </summary>
        public static string GuestStarring {
            get {
                return ResourceManager.GetString("GuestStarring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Adobe Flash Player to use this player..
        /// </summary>
        public static string InstallFlashPlayerToUseThisPlayer {
            get {
                return ResourceManager.GetString("InstallFlashPlayerToUseThisPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        public static string Later {
            get {
                return ResourceManager.GetString("Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest albums.
        /// </summary>
        public static string LatestAlbums {
            get {
                return ResourceManager.GetString("LatestAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest episodes.
        /// </summary>
        public static string LatestEpisodes {
            get {
                return ResourceManager.GetString("LatestEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest movies.
        /// </summary>
        public static string LatestMovies {
            get {
                return ResourceManager.GetString("LatestMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest recordings.
        /// </summary>
        public static string LatestRecordings {
            get {
                return ResourceManager.GetString("LatestRecordings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest tracks.
        /// </summary>
        public static string LatestTracks {
            get {
                return ResourceManager.GetString("LatestTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening to {0}.
        /// </summary>
        public static string ListeningTrack {
            get {
                return ResourceManager.GetString("ListeningTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live TV.
        /// </summary>
        public static string LiveTV {
            get {
                return ResourceManager.GetString("LiveTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log on.
        /// </summary>
        public static string LogOn {
            get {
                return ResourceManager.GetString("LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string LogOnFailed {
            get {
                return ResourceManager.GetString("LogOnFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies.
        /// </summary>
        public static string Movies {
            get {
                return ResourceManager.GetString("Movies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiseat.
        /// </summary>
        public static string Multiseat {
            get {
                return ResourceManager.GetString("Multiseat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure WebMediaPortal for multiseat installations..
        /// </summary>
        public static string MultiseatConfiguration {
            get {
                return ResourceManager.GetString("MultiseatConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can configure the hosts WebMediaPortal connects to here. This is useful in a multiseat setup, where the TV Service and MediaPortal are installed on a different computer. Please make 
        ///sure to install the MPExtended Services on all computers referenced here, and that the username and password have access on all computers..
        /// </summary>
        public static string MultiseatExplanation {
            get {
                return ResourceManager.GetString("MultiseatExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find any servers on your network..
        /// </summary>
        public static string MultiseatNoServersFound {
            get {
                return ResourceManager.GetString("MultiseatNoServersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search on network.
        /// </summary>
        public static string MultiseatSearchOnNetwork {
            get {
                return ResourceManager.GetString("MultiseatSearchOnNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page not found.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        public static string Pictures {
            get {
                return ResourceManager.GetString("Pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your username and password..
        /// </summary>
        public static string PleaseEnterUsernameAndPassword {
            get {
                return ResourceManager.GetString("PleaseEnterUsernameAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        public static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; till &lt;strong&gt;{1}&lt;/strong&gt; on channel &lt;strong&gt;{2}&lt;/strong&gt;.
        /// </summary>
        public static string ProgramChannelDetails {
            get {
                return ResourceManager.GetString("ProgramChannelDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded on.
        /// </summary>
        public static string RecordedOn {
            get {
                return ResourceManager.GetString("RecordedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordings.
        /// </summary>
        public static string Recordings {
            get {
                return ResourceManager.GetString("Recordings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time.
        /// </summary>
        public static string ScheduleHeaderEndTime {
            get {
                return ResourceManager.GetString("ScheduleHeaderEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetition.
        /// </summary>
        public static string ScheduleHeaderRepetition {
            get {
                return ResourceManager.GetString("ScheduleHeaderRepetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        public static string ScheduleHeaderStartTime {
            get {
                return ResourceManager.GetString("ScheduleHeaderStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules.
        /// </summary>
        public static string Schedules {
            get {
                return ResourceManager.GetString("Schedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string SearchFieldPlaceholder {
            get {
                return ResourceManager.GetString("SearchFieldPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching.
        /// </summary>
        public static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season {0}.
        /// </summary>
        public static string Season {
            get {
                return ResourceManager.GetString("Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shares.
        /// </summary>
        public static string Shares {
            get {
                return ResourceManager.GetString("Shares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} season {1}.
        /// </summary>
        public static string ShowSeason {
            get {
                return ResourceManager.GetString("ShowSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occurred while processing your request..
        /// </summary>
        public static string SorryAnErrorOccurred {
            get {
                return ResourceManager.GetString("SorryAnErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, the page you requested doesn&apos;t exist. .
        /// </summary>
        public static string SorryPageNotFound {
            get {
                return ResourceManager.GetString("SorryPageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, your search didn&apos;t yield any results..
        /// </summary>
        public static string SorryYourSearchDidNotYieldAnyResults {
            get {
                return ResourceManager.GetString("SorryYourSearchDidNotYieldAnyResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specials.
        /// </summary>
        public static string Specials {
            get {
                return ResourceManager.GetString("Specials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming clients.
        /// </summary>
        public static string StreamingClients {
            get {
                return ResourceManager.GetString("StreamingClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System status.
        /// </summary>
        public static string SystemStatus {
            get {
                return ResourceManager.GetString("SystemStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagline.
        /// </summary>
        public static string Tagline {
            get {
                return ResourceManager.GetString("Tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s schedules.
        /// </summary>
        public static string TodaysSchedules {
            get {
                return ResourceManager.GetString("TodaysSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Guide.
        /// </summary>
        public static string TVGuide {
            get {
                return ResourceManager.GetString("TVGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Server status.
        /// </summary>
        public static string TVServerStatus {
            get {
                return ResourceManager.GetString("TVServerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Shows.
        /// </summary>
        public static string TVShows {
            get {
                return ResourceManager.GetString("TVShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading update information.
        /// </summary>
        public static string UpdateCheckerError {
            get {
                return ResourceManager.GetString("UpdateCheckerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates available.
        /// </summary>
        public static string UpdateCheckerNoUpdates {
            get {
                return ResourceManager.GetString("UpdateCheckerNoUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available: version {0}.
        /// </summary>
        public static string UpdateCheckerUpdate {
            get {
                return ResourceManager.GetString("UpdateCheckerUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is WebMediaPortal &lt;strong&gt;{0}&lt;/strong&gt;..
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enable deinterlacing.
        /// </summary>
        public static string VLCEnableDeinterlacing {
            get {
                return ResourceManager.GetString("VLCEnableDeinterlacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pause.
        /// </summary>
        public static string VLCPause {
            get {
                return ResourceManager.GetString("VLCPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play.
        /// </summary>
        public static string VLCPlay {
            get {
                return ResourceManager.GetString("VLCPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop.
        /// </summary>
        public static string VLCStop {
            get {
                return ResourceManager.GetString("VLCStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to switch fullscreen.
        /// </summary>
        public static string VLCSwitchFullscreen {
            get {
                return ResourceManager.GetString("VLCSwitchFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your VLC version is too old to support deinterlacing in the browser. Update to version 1.1.11 or higher..
        /// </summary>
        public static string VLCTooOldToSupportDeinterlacing {
            get {
                return ResourceManager.GetString("VLCTooOldToSupportDeinterlacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watched.
        /// </summary>
        public static string Watched {
            get {
                return ResourceManager.GetString("Watched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watching {0}.
        /// </summary>
        public static string WatchingEpisode {
            get {
                return ResourceManager.GetString("WatchingEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watching {0}.
        /// </summary>
        public static string WatchingMovie {
            get {
                return ResourceManager.GetString("WatchingMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watching {0} on {1}.
        /// </summary>
        public static string WatchingProgram {
            get {
                return ResourceManager.GetString("WatchingProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watching {0}.
        /// </summary>
        public static string WatchingRecording {
            get {
                return ResourceManager.GetString("WatchingRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch live.
        /// </summary>
        public static string WatchLive {
            get {
                return ResourceManager.GetString("WatchLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome &lt;strong&gt;{0}&lt;/strong&gt;!.
        /// </summary>
        public static string WelcomeUsername {
            get {
                return ResourceManager.GetString("WelcomeUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written by:.
        /// </summary>
        public static string WrittenBy {
            get {
                return ResourceManager.GetString("WrittenBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are listening to &lt;strong&gt;{0}&lt;/strong&gt; by &lt;strong&gt;{1}&lt;/strong&gt;..
        /// </summary>
        public static string YouAreListening {
            get {
                return ResourceManager.GetString("YouAreListening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are watching &lt;strong&gt;{0} - Season {1} Episode {2} - {3}&lt;/strong&gt;..
        /// </summary>
        public static string YouAreWatchingEpisode {
            get {
                return ResourceManager.GetString("YouAreWatchingEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are watching to &lt;strong&gt;{0}&lt;/strong&gt;..
        /// </summary>
        public static string YouAreWatchingMovie {
            get {
                return ResourceManager.GetString("YouAreWatchingMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are watching &lt;strong&gt;{0}&lt;/strong&gt; on &lt;strong&gt;{1}&lt;/strong&gt;..
        /// </summary>
        public static string YouAreWatchingProgram {
            get {
                return ResourceManager.GetString("YouAreWatchingProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are watching &lt;strong&gt;{0}&lt;/strong&gt;..
        /// </summary>
        public static string YouAreWatchingRecording {
            get {
                return ResourceManager.GetString("YouAreWatchingRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your artists.
        /// </summary>
        public static string YourArtists {
            get {
                return ResourceManager.GetString("YourArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your movies.
        /// </summary>
        public static string YourMovies {
            get {
                return ResourceManager.GetString("YourMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your recordings.
        /// </summary>
        public static string YourRecordings {
            get {
                return ResourceManager.GetString("YourRecordings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your TV shows.
        /// </summary>
        public static string YourTVShows {
            get {
                return ResourceManager.GetString("YourTVShows", resourceCulture);
            }
        }
    }
}
