//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPExtended.Applications.WebMediaPortal.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MPExtended.Applications.WebMediaPortal.Strings.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        public static string AccountInformation {
            get {
                return ResourceManager.GetString("AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add schedule.
        /// </summary>
        public static string AddSchedule {
            get {
                return ResourceManager.GetString("AddSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aired {0}.
        /// </summary>
        public static string Aired {
            get {
                return ResourceManager.GetString("Aired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} by {1}.
        /// </summary>
        public static string AlbumBy {
            get {
                return ResourceManager.GetString("AlbumBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s albums.
        /// </summary>
        public static string AlbumsFromArtist {
            get {
                return ResourceManager.GetString("AlbumsFromArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel schedule.
        /// </summary>
        public static string CancelSchedule {
            get {
                return ResourceManager.GetString("CancelSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        public static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card details.
        /// </summary>
        public static string CardDetails {
            get {
                return ResourceManager.GetString("CardDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grabbing EPG.
        /// </summary>
        public static string CardGrabbingEPG {
            get {
                return ResourceManager.GetString("CardGrabbingEPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card name.
        /// </summary>
        public static string CardName {
            get {
                return ResourceManager.GetString("CardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording file.
        /// </summary>
        public static string CardRecordingFile {
            get {
                return ResourceManager.GetString("CardRecordingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTSP stream.
        /// </summary>
        public static string CardRTSPStream {
            get {
                return ResourceManager.GetString("CardRTSPStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuner cards.
        /// </summary>
        public static string Cards {
            get {
                return ResourceManager.GetString("Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrambled.
        /// </summary>
        public static string CardScrambled {
            get {
                return ResourceManager.GetString("CardScrambled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string CardState {
            get {
                return ResourceManager.GetString("CardState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeshifting file.
        /// </summary>
        public static string CardTimeshiftingFile {
            get {
                return ResourceManager.GetString("CardTimeshiftingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        public static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string CreateSchedule {
            get {
                return ResourceManager.GetString("CreateSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string DiskInfoAvailable {
            get {
                return ResourceManager.GetString("DiskInfoAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk.
        /// </summary>
        public static string DiskInfoDisk {
            get {
                return ResourceManager.GetString("DiskInfoDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk information.
        /// </summary>
        public static string DiskInformation {
            get {
                return ResourceManager.GetString("DiskInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string DiskInfoSize {
            get {
                return ResourceManager.GetString("DiskInfoSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        public static string DiskInfoUsed {
            get {
                return ResourceManager.GetString("DiskInfoUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download playlist (.m3u) for usage with external player.
        /// </summary>
        public static string DownloadPlaylist {
            get {
                return ResourceManager.GetString("DownloadPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earlier.
        /// </summary>
        public static string Earlier {
            get {
                return ResourceManager.GetString("Earlier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit schedule.
        /// </summary>
        public static string EditSchedule {
            get {
                return ResourceManager.GetString("EditSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Episode {0} - {1}.
        /// </summary>
        public static string EpisodeDisplay {
            get {
                return ResourceManager.GetString("EpisodeDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the information below when you report this error..
        /// </summary>
        public static string ErrorPageText {
            get {
                return ResourceManager.GetString("ErrorPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest starring:.
        /// </summary>
        public static string GuestStarring {
            get {
                return ResourceManager.GetString("GuestStarring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Adobe Flash Player to use this player..
        /// </summary>
        public static string InstallFlashPlayerToUseThisPlayer {
            get {
                return ResourceManager.GetString("InstallFlashPlayerToUseThisPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        public static string Later {
            get {
                return ResourceManager.GetString("Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest episodes.
        /// </summary>
        public static string LatestEpisodes {
            get {
                return ResourceManager.GetString("LatestEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest movies.
        /// </summary>
        public static string LatestMovies {
            get {
                return ResourceManager.GetString("LatestMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest recordings.
        /// </summary>
        public static string LatestRecordings {
            get {
                return ResourceManager.GetString("LatestRecordings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live TV.
        /// </summary>
        public static string LiveTV {
            get {
                return ResourceManager.GetString("LiveTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log on.
        /// </summary>
        public static string LogOn {
            get {
                return ResourceManager.GetString("LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string LogOnFailed {
            get {
                return ResourceManager.GetString("LogOnFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies.
        /// </summary>
        public static string Movies {
            get {
                return ResourceManager.GetString("Movies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your username and password..
        /// </summary>
        public static string PleaseEnterUsernameAndPassword {
            get {
                return ResourceManager.GetString("PleaseEnterUsernameAndPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        public static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; till &lt;strong&gt;{1}&lt;/strong&gt; on channel &lt;strong&gt;{2}&lt;/strong&gt;.
        /// </summary>
        public static string ProgramChannelDetails {
            get {
                return ResourceManager.GetString("ProgramChannelDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recorded on:.
        /// </summary>
        public static string RecordedOn {
            get {
                return ResourceManager.GetString("RecordedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordings.
        /// </summary>
        public static string Recordings {
            get {
                return ResourceManager.GetString("Recordings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time.
        /// </summary>
        public static string ScheduleHeaderEndTime {
            get {
                return ResourceManager.GetString("ScheduleHeaderEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repetition.
        /// </summary>
        public static string ScheduleHeaderRepetition {
            get {
                return ResourceManager.GetString("ScheduleHeaderRepetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        public static string ScheduleHeaderStartTime {
            get {
                return ResourceManager.GetString("ScheduleHeaderStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules.
        /// </summary>
        public static string Schedules {
            get {
                return ResourceManager.GetString("Schedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string SearchFieldPlaceholder {
            get {
                return ResourceManager.GetString("SearchFieldPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season {0}.
        /// </summary>
        public static string Season {
            get {
                return ResourceManager.GetString("Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} season {1}.
        /// </summary>
        public static string ShowSeason {
            get {
                return ResourceManager.GetString("ShowSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occurred while processing your request..
        /// </summary>
        public static string SorryAnErrorOccurred {
            get {
                return ResourceManager.GetString("SorryAnErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, your search didn&apos;t yield any results..
        /// </summary>
        public static string SorryYourSearchDidNotYieldAnyResults {
            get {
                return ResourceManager.GetString("SorryYourSearchDidNotYieldAnyResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming clients.
        /// </summary>
        public static string StreamingClients {
            get {
                return ResourceManager.GetString("StreamingClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s schedules.
        /// </summary>
        public static string TodaysSchedules {
            get {
                return ResourceManager.GetString("TodaysSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Guide.
        /// </summary>
        public static string TVGuide {
            get {
                return ResourceManager.GetString("TVGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Server status.
        /// </summary>
        public static string TVServerStatus {
            get {
                return ResourceManager.GetString("TVServerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Shows.
        /// </summary>
        public static string TVShows {
            get {
                return ResourceManager.GetString("TVShows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enable deinterlacing.
        /// </summary>
        public static string VLCEnableDeinterlacing {
            get {
                return ResourceManager.GetString("VLCEnableDeinterlacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen might not work with your VLC version. Downgrade to VLC 1.0.x if you want fullscreen; but then you loose deinterlace support..
        /// </summary>
        public static string VLCFullscreenNotSupported {
            get {
                return ResourceManager.GetString("VLCFullscreenNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pause.
        /// </summary>
        public static string VLCPause {
            get {
                return ResourceManager.GetString("VLCPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to play.
        /// </summary>
        public static string VLCPlay {
            get {
                return ResourceManager.GetString("VLCPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop.
        /// </summary>
        public static string VLCStop {
            get {
                return ResourceManager.GetString("VLCStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to switch fullscreen.
        /// </summary>
        public static string VLCSwitchFullscreen {
            get {
                return ResourceManager.GetString("VLCSwitchFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your VLC version is too old to support deinterlacing in the browser. Update to version 1.1.0 or higher; but then you loose fullscreen support..
        /// </summary>
        public static string VLCTooOldToSupportDeinterlacing {
            get {
                return ResourceManager.GetString("VLCTooOldToSupportDeinterlacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watching {0}.
        /// </summary>
        public static string WatchingEpisode {
            get {
                return ResourceManager.GetString("WatchingEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watching {0}.
        /// </summary>
        public static string WatchingMovie {
            get {
                return ResourceManager.GetString("WatchingMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watching {0} on {1}.
        /// </summary>
        public static string WatchingProgram {
            get {
                return ResourceManager.GetString("WatchingProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watching {0}.
        /// </summary>
        public static string WatchingRecording {
            get {
                return ResourceManager.GetString("WatchingRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome &lt;strong&gt;{0}&lt;/strong&gt;!.
        /// </summary>
        public static string WelcomeUsername {
            get {
                return ResourceManager.GetString("WelcomeUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written by:.
        /// </summary>
        public static string WrittenBy {
            get {
                return ResourceManager.GetString("WrittenBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are watching &lt;strong&gt;{0} - Season {1} Episode {2} - {3}&lt;/strong&gt;.
        /// </summary>
        public static string YouAreWatchingEpisode {
            get {
                return ResourceManager.GetString("YouAreWatchingEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are watching to &lt;strong&gt;{0}&lt;/strong&gt;.
        /// </summary>
        public static string YouAreWatchingMovie {
            get {
                return ResourceManager.GetString("YouAreWatchingMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are watching &lt;strong&gt;{0}&lt;/strong&gt;on &lt;strong&gt;{1}&lt;/strong&gt;.
        /// </summary>
        public static string YouAreWatchingProgram {
            get {
                return ResourceManager.GetString("YouAreWatchingProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are watching &lt;strong&gt;{0}&lt;/strong&gt;.
        /// </summary>
        public static string YouAreWatchingRecording {
            get {
                return ResourceManager.GetString("YouAreWatchingRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your artists.
        /// </summary>
        public static string YourArtists {
            get {
                return ResourceManager.GetString("YourArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your movies.
        /// </summary>
        public static string YourMovies {
            get {
                return ResourceManager.GetString("YourMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your recordings.
        /// </summary>
        public static string YourRecordings {
            get {
                return ResourceManager.GetString("YourRecordings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your TV shows.
        /// </summary>
        public static string YourTVShows {
            get {
                return ResourceManager.GetString("YourTVShows", resourceCulture);
            }
        }
    }
}
