name: MP Extended / Release

on:
  push:
    # On Tag / Release by Mask
    tags:
      - "v*"

jobs:
  build:
    uses: ./.github/workflows/mpextended.yml
  
  release:
    strategy:
      matrix:
        architecture: [x86, x64]

    name: Release MP Extended ${{ matrix.architecture }}
    needs: build
    permissions:
      contents: write
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Download Artifacts / MPExtended service
        uses: actions/download-artifact@v4
        with:
          name: MPExtended service ${{ matrix.architecture }}
          path: release-files

      - name: Download Artifacts / WebMediaPortal
        uses: actions/download-artifact@v4
        with:
          name: WebMediaPortal ${{ matrix.architecture }}
          path: release-files

      - name: Download Artifacts / WebMediaPortal IIS
        uses: actions/download-artifact@v4
        with:
          name: WebMediaPortal IIS ${{ matrix.architecture }}
          path: release-files

      - name: x64 Artifacts
        if: ${{ matrix.architecture == 'x64' }}
        run: |
          for file in *.msi; do mv -- "$file" "${file%.msi}.x64.msi";done
        working-directory: release-files

      - name: Release ${{ matrix.architecture }}
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release-files/MPExtended.*.msi

  codeql:
    uses: ./.github/workflows/workflow_codeql.yml
    needs: [build, release]
    permissions:
      security-events: write

  ci-status:
    name: Status
    runs-on: ubuntu-latest
    needs:
      - build
      - release
      - codeql
    if: always()
    steps:
      - name: Success
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failure
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
